import {registerTempImageServices} from '../temp-image-upload';
import {relayService} from '../relay-services';
import {dialog,BrowserWindow} from 'electron';
import fs from 'node:fs/promises';
import path from 'node:path';
import type {ImageAttachment} from '../../shared/types';
import type {PluginManager} from './manager';
const object={type:'object'};

/**
 * Host-side plugin APIs must never accept an arbitrary working directory.
 * The plugin call context is the only source of the project directory; these
 * guards only validate that it is a real directory and that any optional Git
 * path stays relative to it.
 */
async function assertProjectDirectory(project:string):Promise<void>{
 if(typeof project!=='string'||!project||!path.isAbsolute(project)||project.includes('\0'))throw Error('Invalid project directory');
 const stat=await fs.stat(project).catch(()=>null);
 if(!stat?.isDirectory())throw Error('Project directory is unavailable');
}
function projectRelativePath(value:unknown):string{
 if(typeof value!=='string'||!value||value.length>1000||value.includes('\0')||path.isAbsolute(value)||/^[A-Za-z]:[\\/]/.test(value))throw Error('Git path must be relative to the project');
 const parts=value.replaceAll('\\','/').split('/');
 if(parts.some(part=>part==='..'))throw Error('Git path may not escape the project');
 return value;
}
function gitRef(value:unknown,field='Git ref'):string{
 if(typeof value!=='string'||!value||value.length>300||value.startsWith('-')||/[\0\r\n]/.test(value))throw Error(`${field} is invalid`);
 return value;
}
/** 读 Git 内置插件配置（项目覆盖优先，回退全局，再回退默认值）；失败不阻断主流程 */
async function gitSetting(projectPath:string,key:string):Promise<string|number|boolean|undefined>{
 try{const {readSettings}=await import('../main');const {builtinSettingValue}=await import('../../shared/builtin-plugins');return builtinSettingValue(await readSettings(),projectPath,'git',key);}catch{return undefined;}
}
function imageInput(value:unknown):ImageAttachment[]{
 if(!Array.isArray(value)||value.length<1||value.length>8)throw Error('One to eight images are required');
 let total=0;
 return value.map((item:any)=>{
  if(!item||typeof item!=='object'||typeof item.name!=='string'||typeof item.mimeType!=='string'||typeof item.dataBase64!=='string')throw Error('Invalid image attachment');
  if(!/^image\/(?:png|jpeg|gif|webp)$/i.test(item.mimeType))throw Error('Only PNG, JPEG, GIF and WebP images are supported');
  if(item.name.length>200||item.dataBase64.length>10*1024*1024||!/^[A-Za-z0-9+/=_-]+$/.test(item.dataBase64))throw Error('Invalid image data');
  total+=item.dataBase64.length;
  if(total>12*1024*1024)throw Error('Image attachments exceed 12 MB');
  return {name:item.name,mimeType:item.mimeType,dataBase64:item.dataBase64};
 });
}
export function registerHostServices(m:PluginManager,isAppSender:(id:number)=>boolean){
 registerTempImageServices(m,async()=>{const {readSettings}=await import('../main');return relayService(await readSettings());});
 m.host.set('mcp.servers',{permission:'mcp.connect',description:'List enabled MCP connections without secrets',input:object,run:async()=>{const {readSettings}=await import('../main');return ((await readSettings()).mcpServers??[]).filter(s=>s.enabled).map(s=>({id:s.id,name:s.name,transport:s.transport}));}});
 for(const action of ['tools','call'])m.host.set(`mcp.${action}`,{permission:'mcp.connect',description:`Configured MCP server ${action}`,input:{type:'object',properties:{serverId:{type:'string'},name:{type:'string'},arguments:{type:'object'}},required:action==='call'?['serverId','name']:['serverId'],additionalProperties:false},run:async(a)=>{const {readSettings}=await import('../main');const s=((await readSettings()).mcpServers??[]).find(s=>s.enabled&&s.id===a.serverId);if(!s)throw Error('Enabled MCP server not found');return (await import('../mcp-client')).configuredMcp(s,action==='call'?a.name:undefined,a.arguments);}});
 m.host.set('models.generate',{permission:'models.use',description:'Generate text with the current project model; credentials never leave the host',input:{type:'object',properties:{prompt:{type:'string',maxLength:120000},providerId:{type:'string'},modelId:{type:'string'}},required:['prompt'],additionalProperties:false},run:async(a,c)=>{
  if((!a.providerId||!a.modelId)&&c.chain.some(id=>m.packages(c.project).get(id)?.manifest.extensions?.some(e=>e.point==='sage/models.route')))throw Error('Model routers must choose an explicit base provider/model for planning');
  const {resolveModel}=await import('../model-resolver');let selectedModel;if(a.providerId||a.modelId){const {readSettings}=await import('../main');const p=(await readSettings()).modelProviders?.find(p=>p.enabled&&p.id===a.providerId);if(p?.routingExtension)throw Error('Model generation requires a base provider, not a routing provider');if(!p?.models.includes(a.modelId))throw Error('Unknown enabled provider/model');selectedModel={providerId:a.providerId,modelId:a.modelId};}const model=await resolveModel({projectPath:c.project,convMeta:selectedModel?{selectedModel} as any:undefined});if(!model)throw Error('Configure a project model first');
 const signal=AbortSignal.timeout(Math.max(1,c.deadline-Date.now()));const opts={cwd:c.project,prompt:a.prompt,model:model.model,apiKey:model.apiKey,baseUrl:model.baseUrl,relayTransport:model.relayTransport,signal};const result=model.protocol==='openai'?await (await import('../openai-api-bridge')).runOpenAIAPI(opts):await (await import('../claude-api-bridge')).runClaudeAPI(opts);if(result.error)throw Error(result.error);return {text:result.text};
 }});
 m.host.set('models.analyzeImage',{permission:'models.use',description:'Analyze supplied images with the configured vision model; image data and credentials stay in the host process',input:{type:'object',properties:{images:{type:'array',items:{type:'object',properties:{name:{type:'string',maxLength:200},mimeType:{type:'string',maxLength:50},dataBase64:{type:'string',maxLength:10*1024*1024}},required:['name','mimeType','dataBase64'],additionalProperties:false}},prompt:{type:'string',maxLength:30000},timeoutMs:{type:'integer',minimum:1000,maximum:30000}},required:['images'],additionalProperties:false},run:async(a,c)=>{
  const images=imageInput(a.images),remaining=Math.max(1,c.deadline-Date.now()),timeout=Math.min(a.timeoutMs??30000,remaining);const {analyzeImages}=await import('../image-analyzer');const text=await analyzeImages(images,a.prompt,{source:'other',projectPath:c.project,label:`plugin:${c.chain.at(-1)??'unknown'} image analysis`},undefined,timeout);return {analyzed:Boolean(text),text:text??''};
 }});
 // Git is intentionally exposed as a small, project-scoped API. It does not
 // accept cwd/repository arguments, and write access is limited to an
 // explicit list of relative paths when staging for a commit.
 m.host.set('git.status',{permission:'workspace.read',description:'Read Git status for the current project',input:object,run:async(_a,c)=>{await assertProjectDirectory(c.project);const {gitStatus,gitCurrentBranch}=await import('../git-utils');const [files,branch]=await Promise.all([gitStatus(c.project),gitCurrentBranch(c.project)]);return {branch,files};}});
 m.host.set('git.diff',{permission:'workspace.read',description:'Read a Git diff for the current project',input:{type:'object',properties:{ref1:{type:'string',maxLength:300},ref2:{type:'string',maxLength:300},path:{type:'string',maxLength:1000}},additionalProperties:false},run:async(a,c)=>{await assertProjectDirectory(c.project);const ref1=a.ref1===undefined?undefined:gitRef(a.ref1,'ref1'),ref2=a.ref2===undefined?undefined:gitRef(a.ref2,'ref2'),file=a.path===undefined?undefined:projectRelativePath(a.path);const {gitDiff,gitFileDiff}=await import('../git-utils');const text=file?await gitFileDiff(c.project,file,ref1,ref2):await gitDiff(c.project,ref1,ref2);return {text};}});
 m.host.set('git.log',{permission:'workspace.read',description:'Read bounded Git history for the current project',input:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:200},skip:{type:'integer',minimum:0,maximum:10000},ref:{type:'string',maxLength:300},path:{type:'string',maxLength:1000}},additionalProperties:false},run:async(a,c)=>{await assertProjectDirectory(c.project);const opts={limit:a.limit===undefined?50:a.limit,skip:a.skip===undefined?0:a.skip,ref:a.ref===undefined?undefined:gitRef(a.ref,'ref'),path:a.path===undefined?undefined:projectRelativePath(a.path)};const {gitLog}=await import('../git-utils');return {commits:await gitLog(c.project,opts)};}});
 m.host.set('git.commit',{permission:'workspace.write',description:'Commit current Git changes; optional paths are staged explicitly first',input:{type:'object',properties:{message:{type:'string',minLength:1,maxLength:500},paths:{type:'array',items:{type:'string',maxLength:1000}}},required:['message'],additionalProperties:false},run:async(a,c)=>{await assertProjectDirectory(c.project);let paths: string[]=[];if(a.paths!==undefined){if(!Array.isArray(a.paths)||a.paths.length>100)throw Error('At most 100 Git paths may be staged');paths=a.paths.map(projectRelativePath);const {gitStage}=await import('../git-utils');await gitStage(c.project,paths);}const {gitCommit}=await import('../git-utils');return {output:await gitCommit(c.project,a.message),stagedPaths:paths};}});
 m.host.set('git.config',{permission:'workspace.read',description:'Read user Git plugin preferences (branch prefix, push/commit guidance)',input:object,run:async(_a,c)=>{await assertProjectDirectory(c.project);const [branchPrefix,forceWithLease,commitHint]=await Promise.all([gitSetting(c.project,'branchPrefix'),gitSetting(c.project,'forceWithLease'),gitSetting(c.project,'commitHint')]);return {branchPrefix:String(branchPrefix??''),forceWithLease:forceWithLease===true,commitHint:String(commitHint??'')};}});
 m.host.set('git.branch',{permission:'workspace.write',description:'Create and check out a project branch',input:{type:'object',properties:{name:{type:'string',maxLength:200},base:{type:'string',maxLength:300}},required:['name'],additionalProperties:false},run:async(a,c)=>{await assertProjectDirectory(c.project);const {gitBranchCreate,applyBranchPrefix}=await import('../git-utils');const raw=gitRef(a.name,'Branch name');const prefix=String((await gitSetting(c.project,'branchPrefix'))??'');const name=applyBranchPrefix(raw,prefix);const base=a.base===undefined?undefined:gitRef(a.base,'Base branch');await gitBranchCreate(c.project,name,{base,checkout:true});return {branch:name};}});
 m.host.set('git.push',{permission:'workspace.write',description:'Push the current project branch to its origin remote',input:{type:'object',properties:{setUpstream:{type:'boolean'}},additionalProperties:false},run:async(a,c)=>{await assertProjectDirectory(c.project);const {gitPush}=await import('../git-utils');const forceWithLease=(await gitSetting(c.project,'forceWithLease'))===true;return {output:await gitPush(c.project,{setUpstream:a.setUpstream!==false,forceWithLease})};}});
 m.host.set('conversations.create',{permission:'conversations.write',description:'Create a project conversation',input:{type:'object',properties:{title:{type:'string',maxLength:200}},additionalProperties:false},run:async(a,c)=>{const {newConversation}=await import('../conv-engine');const {saveConv}=await import('../store');const meta=newConversation({projectPath:c.project,title:a.title});await saveConv(meta);return {id:meta.id,title:meta.title};}});
 m.host.set('conversations.read',{permission:'conversations.read',description:'Read a conversation in this project',input:{type:'object',properties:{id:{type:'string'}},required:['id']},run:async(a,c)=>{const {listConvsForProject}=await import('../store');const meta=(await listConvsForProject(c.project)).find(x=>x.id===a.id);if(!meta)throw Error('Conversation not found in this project');return {id:meta.id,title:meta.title,messages:meta.messages};}});
 m.host.set('channels.list',{permission:'channels.send',description:'List configured project channels, without credentials',input:object,run:async(_a,c)=>{const {listChannels}=await import('../store');return (await listChannels(c.project)).map(x=>({id:x.id,name:x.name,type:x.type,enabled:x.enabled}));}});
 m.host.set('channels.send',{permission:'channels.send',description:'Send a message using a configured project channel',input:{type:'object',properties:{id:{type:'string'},text:{type:'string',maxLength:30000}},required:['id','text']},run:async(a,c)=>{const {listChannels}=await import('../store');const channel=(await listChannels(c.project)).find(x=>x.id===a.id&&x.enabled);if(!channel)throw Error('Enabled project channel not found');const {sendViaChannel}=await import('../channels/registry');return sendViaChannel(channel.type,channel.config,{title:'Sage plugin',content:a.text} as any,c.project);}});
 m.host.set('tasks.create',{permission:'tasks.write',description:'Create a scheduled conversation task',input:{type:'object',properties:{name:{type:'string'},prompt:{type:'string'},schedule:{type:'object',properties:{type:{type:'string',enum:['once','interval','hourly','daily','weekly','monthly']},at:{type:'string'},intervalMinutes:{type:'number',minimum:1},weekday:{type:'integer',minimum:0,maximum:6},monthDay:{type:'integer',minimum:1,maximum:31},minute:{type:'integer',minimum:0,maximum:59}},required:['type'],additionalProperties:false}},required:['name','prompt','schedule']},run:async(a,c)=>{const s=a.schedule;if(s.type==='once'&&(!s.at||!Number.isFinite(Date.parse(s.at))||Date.parse(s.at)<=Date.now()))throw Error('A future ISO date is required');if(s.type==='interval'&&!s.intervalMinutes)throw Error('intervalMinutes required');if(s.type==='hourly'&&s.minute===undefined)throw Error('minute required');if(['daily','weekly','monthly'].includes(s.type)&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.at??''))throw Error('HH:mm time required');if(s.type==='weekly'&&s.weekday===undefined)throw Error('weekday required');if(s.type==='monthly'&&s.monthDay===undefined)throw Error('monthDay required');const scheduler=await import('../scheduler');return scheduler.createScheduledTask(c.project,a.name,a.prompt,a.schedule);}});
 m.host.set('ui.update',{permission:'ui',description:'Update an owned contribution title, badge, visibility or order',input:{type:'object',properties:{contribution:{type:'string'},title:{type:'string',maxLength:120},badge:{type:'string',maxLength:50},visible:{type:'boolean'},order:{type:'integer'}},required:['contribution'],additionalProperties:false},run:async(a,c)=>{const id=c.chain.at(-1)!,p=m.packages(c.project).get(id);if(!p?.manifest.contributes.some(x=>x.id===a.contribution))throw Error('Unknown owned contribution');const key=c.project+'\0'+id,state=m.uiState.get(key)??{};const {contribution,...changes}=a;state[contribution]={...state[contribution],...changes};m.uiState.set(key,state);m.changed();return true;}});
 m.host.set('ui.open',{permission:'ui',description:'Open one of this plugin’s declared views',input:{type:'object',properties:{contribution:{type:'string'}},required:['contribution']},run:async(a,c)=>{const id=c.chain.at(-1)!,p=m.packages(c.project).get(id);const view=p?.manifest.contributes.find(x=>x.id===a.contribution&&x.view);if(!view)throw Error('Unknown owned view');for(const w of BrowserWindow.getAllWindows())if(isAppSender(w.webContents.id))w.webContents.send('plugins:notification',{project:c.project,plugin:id,open:{contribution:view.id,title:view.title}});return true;}});
 // Commands always use the existing project classifier and one-use execution receipt.
 m.host.set('tools.Bash',{permission:'workspace.write',description:'Project shell command with the standard approval and runtime sandbox',input:{type:'object',properties:{command:{type:'string',maxLength:30000},network:{type:'boolean'},networkTargets:{type:'array',minItems:1,maxItems:16,items:{type:'object',properties:{host:{type:'string'},port:{type:'integer',minimum:1,maximum:65535}},required:['host','port'],additionalProperties:false}},networkReason:{type:'string',maxLength:4000},timeout:{type:'number',minimum:1,maximum:30000}},required:['command'],additionalProperties:false},run:async(a,c)=>{
  const {newConversation}=await import('../conv-engine');const meta=newConversation({projectPath:c.project,title:`Plugin ${c.chain.join(' → ')}`});const {decideCommand,approveCommand}=await import('../sandbox/command-decision');const clean={command:a.command,timeout:a.timeout,network:a.network,networkReason:a.networkReason,networkTargets:a.networkTargets};const decision=await decideCommand(clean,meta,AbortSignal.timeout(Math.max(1,c.deadline-Date.now())));if(decision.decision==='deny')throw Error(decision.reason);let input=decision.input;
  if(decision.decision==='ask'){const answer=await dialog.showMessageBox({type:'question',message:'插件请求执行命令',detail:`${c.chain.join(' → ')}\n${c.project}\n\n${clean.command}\n\n${decision.reason}`,buttons:['拒绝',clean.network?'仅本次允许联网':'允许本次'],defaultId:0,cancelId:0});if(answer.response!==1||Date.now()>c.deadline)throw Error('Command denied or expired');input=await approveCommand(decision.input??clean,meta);}
  const {executeTool}=await import('../api-tool-executor');const result=await executeTool('Bash',input,c.project,AbortSignal.timeout(Math.max(1,c.deadline-Date.now())));if(result.isError)throw Error(result.result);return result.result;
 }});
}
