import {resolveLanguage} from '../../shared/language';
import {useEffect,useState} from 'react';
import {DEFAULT_DATE_FORMAT,formatDisplayDateTime,validateDateTime} from '../../shared/date-time';
import {useAppStore} from '../stores/appStore';
export function DateTimeSettings(){
 const settings=useAppStore(s=>s.settings?.dateTime);const en=useAppStore(s=>resolveLanguage(s.settings?.language,s.settings?._systemLocale)==='en');const [zone,setZone]=useState(settings?.timeZone??'system');const [format,setFormat]=useState(settings?.format??DEFAULT_DATE_FORMAT);const [custom,setCustom]=useState(false);const [error,setError]=useState('');const [now,setNow]=useState(Date.now());
 useEffect(()=>{setZone(settings?.timeZone??'system');setFormat(settings?.format??DEFAULT_DATE_FORMAT);},[settings]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
 const save=async(timeZone=zone,pattern=format)=>{try{const value={...settings,timeZone,format:pattern};validateDateTime(value);setError('');await useAppStore.getState().saveSettings({dateTime:value});}catch(e){setError(String((e as Error).message));}};
 const zones=['system','UTC',...((Intl as any).supportedValuesOf?.('timeZone')??['Asia/Shanghai','Asia/Tokyo','Europe/London','America/New_York'])];
 const formats=[DEFAULT_DATE_FORMAT,'YYYY/MM/DD HH:mm','DD/MM/YYYY HH:mm:ss','MM/DD/YYYY hh:mm:ss A',...(!en?['YYYY年MM月DD日 HH:mm:ss']:[]),'YYYY-MM-DD HH:mm:ss Z'];
 return <section className="settings-card" style={{padding:16,marginBottom:18}}><h3 style={{marginTop:0}}>{en?'Date and time':'日期与时间'}</h3><div className="settings-grid-2"><label>{en?'Time zone':'时区'}<input style={{display:'block',width:'100%',boxSizing:'border-box'}} aria-label="时区" list="sage-time-zones" value={zone} onChange={e=>setZone(e.target.value)} onBlur={()=>void save()}/><datalist id="sage-time-zones">{zones.map(z=><option key={z} value={z}>{z==='system'?(en?'Follow system':'跟随系统'):z}</option>)}</datalist><small className="muted">{en?'system follows your computer.':'system 表示跟随系统时区。'}</small></label><label>{en?'Date format':'时间格式'}<select aria-label="时间格式预设" style={{display:'block',width:'100%'}} value={!custom&&formats.includes(format)?format:'custom'} onChange={e=>{if(e.target.value==='custom'){setCustom(true);return;}setCustom(false);setFormat(e.target.value);void save(zone,e.target.value);}}>{formats.map(f=><option key={f} value={f}>{f==='YYYY年MM月DD日 HH:mm:ss'?(en?'Chinese date and time':'中文年月日'):f}</option>)}<option value="custom">{en?'Custom':'自定义'}</option></select>{(custom||!formats.includes(format))&&<input aria-label="自定义时间格式" style={{width:'100%',boxSizing:'border-box',marginTop:6}} maxLength={120} value={format} onChange={e=>setFormat(e.target.value)} onBlur={()=>void save()}/>}</label></div><label><input type="checkbox" checked={settings?.relative!==false} onChange={e=>{void useAppStore.getState().saveSettings({dateTime:{...settings,timeZone:zone,format,relative:e.target.checked}}).catch(error=>setError(String(error)));}}/>{en?'Smart dates: time only today, yesterday label, no year for this year':'智能日期：当天仅显示时间，昨天显示“昨天”，本年省略年份'}</label><p className="muted small">{en?'YYYY year · MM month · DD day · HH 24-hour · hh 12-hour · mm minute · ss second · A AM/PM · Z timezone offset; single letters M/D/H/h omit leading zeros; [text] is literal':'YYYY 年 · MM 月 · DD 日 · HH 24小时 · hh 12小时 · mm 分 · ss 秒 · A AM/PM · Z 时区偏移；单字母 M/D/H/h 省略前导 0；[文字] 原样显示'}</p><p><span className="muted">{en?'Preview: ':'预览：'}</span><strong>{formatDisplayDateTime(now,{...settings,timeZone:zone,format},new Date(now),en?'en':'zh')}</strong></p>{error&&<p role="alert" style={{color:'var(--err)'}}>{error}</p>}</section>;
}
